/** list of cities */
interface City {
    name: string;
}

export const Cities: City[] = [
    { name: 'Acre' },
    { name: 'Afula' },
    { name: 'Arad' },
    { name: 'Arraba' },
    { name: 'Ashdod' },
    { name: 'Baqa al - Gharbiyye' },
    { name: 'Ashkelon' },
    { name: 'Bat Yam' },
    { name: 'Beer sheba' },
    { name: 'Beit Shean' },
    { name: 'Beit Shemesh' },
    { name: 'Bnei Brak' },
    { name: 'Dimona' },
    { name: 'Eilat' },
    { name: `El'ad` },
    { name: `Giv'at Shmuel` },
    { name: 'Givatayim' },
    { name: 'Hadera' },
    { name: 'Haifa' },
    { name: 'Herzliya' },
    { name: 'Hod HaSharon' },
    { name: 'Holon' },
    { name: 'Jerusalem' },
    { name: 'Kafr Qasim' },
    { name: 'Karmiel' },
    { name: 'Kfar Saba' },
    { name: 'Kfar Yona' },
    { name: 'Kiryat Ata' },
    { name: 'Kiryat Bialik' },
    { name: 'Kiryat Gat' },
    { name: 'Kiryat Malakhi' },
    { name: 'Kiryat Motzkin' },
    { name: 'Kiryat Ono' },
    { name: 'Kiryat Shmona' },
    { name: 'Kiryat Yam' },
    { name: 'Lod' },
    { name: `Ma'alot-Tarshiha` },
    { name: 'Migdal HaEmek' },
    { name: `Modi'in-Maccabim-Re'ut` },
    { name: 'Nahariya' },
    { name: 'Nazareth' },
    { name: 'Nesher' },
    { name: 'Ness Ziona' },
    { name: 'Netanya' },
    { name: 'Netivot' },
    { name: 'Nof HaGalil' },
    { name: 'Ofakim' },
    { name: 'Or Akiva' },
    { name: 'Or Yehuda' },
    { name: 'Petah Tikva' },
    { name: 'Qalansawe' },
    { name: `Ra'anana` },
    { name: 'Rahat' },
    { name: 'Ramat Gan' },
    { name: 'Ramat HaSharon' },
    { name: 'Ramla' },
    { name: 'Rehovot' },
    { name: 'Rishon LeZion' },
    { name: 'Rosh HaAyin' },
    { name: 'Safed' },
    { name: 'Sakhnin' },
    { name: 'Sderot' },
    { name: `Shefa - 'Amr` },
    { name: 'Tamra' },
    { name: 'Tayibe' },
    { name: 'Tel Aviv - Yafo' },
    { name: 'Tiberias' },
    { name: 'Tira' },
    { name: 'Tirat Carmel' },
    { name: 'Umm al - Fahm' },
    { name: 'Yavne' },
    { name: 'Yehud - Monosson' },
    { name: 'Yokneam Illit' },
];

